In [1]:
!pip install opendatasets

Requirement already satisfied: opendatasets in c:\users\asrai\anaconda3\lib\site-packages (0.1.22)
Requirement already satisfied: tqdm in c:\users\asrai\anaconda3\lib\site-packages (from opendatasets) (4.62.3)
Requirement already satisfied: click in c:\users\asrai\anaconda3\lib\site-packages (from opendatasets) (8.0.3)
Requirement already satisfied: kaggle in c:\users\asrai\anaconda3\lib\site-packages (from opendatasets) (1.5.12)
Requirement already satisfied: colorama in c:\users\asrai\anaconda3\lib\site-packages (from click->opendatasets) (0.4.4)
Requirement already satisfied: six>=1.10 in c:\users\asrai\anaconda3\lib\site-packages (from kaggle->opendatasets) (1.16.0)
Requirement already satisfied: python-slugify in c:\users\asrai\anaconda3\lib\site-packages (from kaggle->opendatasets) (5.0.2)
Requirement already satisfied: python-dateutil in c:\users\asrai\anaconda3\lib\site-packages (from kaggle->opendatasets) (2.8.2)
Requirement already satisfied: urllib3 in c:\users\asrai\anaconda3\lib\site-packages (from kaggle->opendatasets) (1.26.7)
Requirement already satisfied: requests in c:\users\asrai\anaconda3\lib\site-packages (from kaggle->opendatasets) (2.26.0)
Requirement already satisfied: certifi in c:\users\asrai\anaconda3\lib\site-packages (from kaggle->opendatasets) (2021.10.8)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\asrai\anaconda3\lib\site-packages (from python-slugify->kaggle->opendatasets) (1.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\asrai\anaconda3\lib\site-packages (from requests->kaggle->opendatasets) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\asrai\anaconda3\lib\site-packages (from requests->kaggle->opendatasets) (3.2)

In [2]:
import opendatasets as od
od.download('https://www.kaggle.com/datasets/shivamb/real-or-fake-fake-jobposting-prediction')

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: asraimran13
Your Kaggle Key: ··········
Downloading real-or-fake-fake-jobposting-prediction.zip to ./real-or-fake-fake-jobposting-prediction

100%|██████████| 16.1M/16.1M [00:00<00:00, 214MB/s]

In [3]:
import pandas as pd
import nltk
from nltk import word_tokenize
from nltk import sent_tokenize
from nltk.corpus import stopwords
from nltk.corpus import wordnet
import string
import numpy as np

In [4]:
data=pd.read_csv('/content/real-or-fake-fake-jobposting-prediction/fake_job_postings.csv')
data=data.fillna('0')

In [5]:
data["fraudulent"].value_counts()

0    17014
1      866
Name: fraudulent, dtype: int64

In [6]:
data1=data.iloc[: , 0: 17]
data1

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function
0,1,Marketing Intern,"US, NY, New York",Marketing,0,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,0,0,1,0,Other,Internship,0,0,Marketing
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,0,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,0,Marketing and Advertising,Customer Service
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",0,0,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,0,0,1,0,0,0,0,0,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,0,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales
4,5,Bill Review Manager,"US, FL, Fort Worth",0,0,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17875,17876,Account Director - Distribution,"CA, ON, Toronto",Sales,0,Vend is looking for some awesome new talent to...,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,What can you expect from us?We have an open cu...,0,1,1,Full-time,Mid-Senior level,0,Computer Software,Sales
17876,17877,Payroll Accountant,"US, PA, Philadelphia",Accounting,0,WebLinc is the e-commerce platform and service...,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,Health &amp; WellnessMedical planPrescription ...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Internet,Accounting/Auditing
17877,17878,Project Cost Control Staff Engineer - Cost Con...,"US, TX, Houston",0,0,We Provide Full Time Permanent Positions for m...,Experienced Project Cost Control Staff Enginee...,At least 12 years professional experience.Abil...,0,0,0,0,Full-time,0,0,0,0
17878,17879,Graphic Designer,"NG, LA, Lagos",0,0,0,Nemsia Studios is looking for an experienced v...,1. Must be fluent in the latest versions of Co...,Competitive salary (compensation will be based...,0,0,1,Contract,Not Applicable,Professional,Graphic Design,Design
17879,17880,Web Application Developers,"NZ, N, Wellington",Engineering,0,Vend is looking for some awesome new talent to...,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,0,0,1,1,Full-time,Mid-Senior level,0,Computer Software,Engineering

In [7]:
data2=data.iloc[: ,17:18]
data2

       fraudulent
0               0
1               0
2               0
3               0
4               0
...           ...
17875           0
17876           0
17877           0
17878           0
17879           0

[17880 rows x 1 columns]

In [8]:
data2=data2.replace(0,'fraud')

In [9]:
data2=data2.replace(1,'notfraud')
data2

      fraudulent
0          fraud
1          fraud
2          fraud
3          fraud
4          fraud
...          ...
17875      fraud
17876      fraud
17877      fraud
17878      fraud
17879      fraud

[17880 rows x 1 columns]

In [10]:
import sklearn.preprocessing as sp
import numpy as np
encoding_x=sp.OneHotEncoder()
encoding_y=sp.OneHotEncoder()
Y=encoding_y.fit_transform(np.c_[data2]).toarray()
data2=pd.DataFrame(Y)

In [11]:
X=encoding_x.fit_transform(np.c_[data1]).toarray()
data1=pd.DataFrame(X)

In [12]:
data1=X
data2=Y

In [ ]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y = train_test_split(X ,Y,random_state=42)

In [ ]:
model=models.Sequential()
model.add(layers.Dense(1000,input_dim=69320,activation="relu"))
model.add(layers.Dense(500,activation="relu"))
model.add(layers.Dense(250,activation="relu"))
model.add(layers.Dense(100,activation="relu"))
model.add(layers.Dense(2,activation="Softmax"))
model.summary()

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])

In [ ]:
model.fit(X,Y,epochs=10)

In [ ]:
from sklearn.metrics import confusion_matrix
a=model.predict(test_x)
b=encoding_y.inverse_transform(a)

In [ ]:
c=encoding_y.inverse_transform(test_y)
conf_mx = confusion_matrix(b,c)
conf_mx